#Configuration test
<grid_size> 1 1 1
<grid_spacing> 0.025
<young_modulus> 5e1
<poisson_ratio> 0.2
<time_step> 0.002
<density> 1
<gravity> 0 0 -9.81
<friction> 5
<restitution> 0.0
<display_sphere> 0
<elastic_mode> 2
<plastic_mode> 3
<elastic_method> 4
<damping> 1
<cheat_damping> 0.1
<method> apic
<explicite>