#Configuration test
<grid_size> 1 1 1
<grid_spacing> 0.025
<young_modulus> 3e+1
<poisson_ratio> 0.2
<time_step> 0.001
<density> 1
<hardenning> 35 1.01 10 10
<gravity> 0 0 -9.81
<friction> 10
<display_sphere> 0
<elastic_mode> 2
<plastic_mode> 3
<damping> 1
<cheat_damping> 0.1
<method> apic
<explicite>