#Configuration test
<grid_size> 1 1 1
<grid_spacing> 0.025
<young_modulus> 1.4e5
<poisson_ratio> 0.2
<time_step> 0.001
<density> 400
<gravity> 0 0 -10
<friction> 5
<hardenning> 25 0 0.02 10
<display_sphere> 1
<elastic_mode> 2
<plastic_mode> 3
<elastic_method> 5
<damping> 0.0
<cheat_damping> 1
<stretch_max> 1.0075 1.0075 1.0075
<stretch_min> 0.975 0.975 0.975
<method> apic
<explicite>