#Configuration test
<grid_size> 1 1 1
<grid_spacing> 0.025
<bm> 109.0e3
<sm> 11.2e3
<sy> 0.1
<hb> 2.80
<eta> 10.0
<time_step> 0.0001
<density> 1000.0
<gravity> 0 0 -10
<friction> 1
<display_sphere> 1
<ad> 5
<elastic_mode> 2
<plastic_mode> 3
<elastic_method> 5
<damping> 0.0
<cheat_damping> 1
<method> apic
<fr> 0.01
<explicite>