# Gooey thingy
<grid_size> 1 1 1
<grid_spacing> 0.01
<young_modulus_vec> 1e2 1e2 1e2
<poisson_ratio_vec> 0.4 0.4 0.4
<time_step> 0.0002 
<density> 0.5
<hardenning> 25 0 0.02 10
<gravity> 0 0 -9.81
<friction> 0
<display_sphere> 1
<elastic_mode> 2
<plastic_mode> 2
<damping> 10
<cheat_damping> 0.1
<smooth_velocity> 0
<method> apic
<stretch_max> 0.0025 1.0 1.0075
<stretch_min> 0.975 0.975 0.975
<anisotropy> 1 1 1 